---
title: "case_study"
author: "Farizah Rob"
date: "2022-10-13"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position="bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete <- scale_color_viridis_d
scale_fill_discrete <- scale_fill_viridis_d
```

### Get data

```{r}
library(p8105.datasets)

data(nyc_airbnb) #17 variables, 40753 variables

nyc_airbnb <- 
  nyc_airbnb %>% 
  rename(borough = neighbourhood_group) %>%
  mutate(stars = review_scores_location / 2)
```

## Brainstorm ideas

* what variables are relevant to higher reviews?
* what are the popular places to rent an airbnb?
* what portion of hosts/locations are private rooms vs entire apartment vs shared room? (room_type)
* what makes an airbnb more expensive?

```{r}
nyc_airbnb %>%
  ggplot(aes(x = borough, y = review_scores_location)) + geom_point() #does not tell us much

nyc_airbnb %>%
  group_by(borough) %>%
  summarize(avg_review = mean(stars, na.rm=TRUE)) %>%
  knitr::kable()

#Most number in Williamsburg, Bed-Stuy, Harlem, Bushwick
nyc_airbnb %>%
  group_by(neighbourhood, borough) %>%
  distinct() %>%
  summarize(n_obs = n()) %>%
  filter(n_obs > 100) %>%
  arrange(n_obs)

#Bronx has lowest average review score but all are comparable
# Hunts Point has lowest average review score amongst all neighborhoods in Bronx

nyc_airbnb %>%
  filter(borough=="Bronx") %>%
  group_by(neighbourhood) %>%
  summarize(avg_review = mean(stars, na.rm = TRUE)) %>%
  knitr::kable()

#Looking at Brooklyn next
# Brownsville has lowest average review amongst Brooklyn neighborhoods
nyc_airbnb %>%
  filter(borough=="Brooklyn") %>%
  group_by(neighbourhood) %>%
  summarize(avg_review = mean(stars, na.rm = TRUE)) %>%
  arrange(avg_review) %>%
  knitr::kable()

#Manhattan
#East Harlem followed by Inwood has lowest review amongst Manhattan neighborhoods
nyc_airbnb %>%
  filter(borough=="Manhattan") %>%
  group_by(neighbourhood) %>%
  summarize(avg_review = mean(stars, na.rm = TRUE)) %>%
  arrange(avg_review) %>%
  knitr::kable()

#total private rooms, shared room, entire apartment
#Entire home/apartment and Private room (similar numbers), only 1190 shared room 

nyc_airbnb %>%
  group_by(room_type) %>%
  summarize(count = n())
```
Let's look at price..

```{r}
# you can also use summarize without grouping first
nyc_airbnb %>%
  group_by(borough, room_type) %>%
  summarize(
    mean_price = mean(price, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = "room_type", 
    values_from = "mean_price"
  ) 
```

Look at price distributions 

```{r}
nyc_airbnb %>%
  filter(borough=="Manhattan", 
         room_type=="Entire home/apt", 
         price < 1000) %>%
  ggplot(aes(x = price)) + geom_histogram()

nyc_airbnb %>%
  filter(borough == "Manhattan", 
         price < 1000) %>%
  ggplot(aes(x = price)) + geom_histogram() + facet_grid(. ~ room_type)
```

Price vs.. rating? 

```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan") %>%
  ggplot(aes(x = stars, y = price)) + geom_point() + facet_grid(. ~ room_type)
```

Somewhat fancy plot

```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan") %>%
  group_by(neighbourhood) %>%
  summarize(mean_price = mean(price, na.rm = TRUE)) %>%
  arrange(desc(mean_price))
```

```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan", 
         price <= 1000, 
         room_type == "Entire home/apt") %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  ggplot(aes(x = neighbourhood, y = price)) + geom_boxplot() + coord_flip()
```

Price vs location 

```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan", 
         price <= 1000, 
         room_type == "Entire home/apt") %>%
  sample_n(1000) %>%
  ggplot(aes(x = lat, y = long, color = price)) + geom_point(alpha = 0.5)

#northern manhattan is on the right top, southern manhattan is left bottom
```

