---
title: "numeric_eda"
author: "Farizah Rob"
date: "2022-10-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

## Registered S3 method overwritten by 'hoardr':
##   method           from
##   print.cache_info httr
## using cached file: ~/Library/Caches/R/noaa_ghcnd/USW00094728.dly
## date created (size, mb): 2022-04-04 04:13:35 (7.647)
## file min/max dates: 1869-01-01 / 2022-04-30
## using cached file: ~/Library/Caches/R/noaa_ghcnd/USC00519397.dly
## date created (size, mb): 2022-04-04 04:13:39 (1.697)
## file min/max dates: 1965-01-01 / 2020-02-29
## using cached file: ~/Library/Caches/R/noaa_ghcnd/USS0023B17S.dly
## date created (size, mb): 2022-04-04 04:13:42 (0.93)
## file min/max dates: 1999-09-01 / 2022-03-31
```

## `group_by()`

```{r}
weather_df %>% 
  group_by(name, month)
```

## `summarize()`

let's group and then summarize! 

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n()
  )
```
can we count in other ways?

```{r}
weather_df %>%
  count(name, month)

```

don't use `table()`

```{r}
#don't do this
weather_df %>%
  pull(month) %>% 
  table
```

you can have multiple summaries 

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(), 
    n_dist = n_distinct(date)
  )
```

## a brief aside on 2x2 tables

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(n_obs = n()) %>% 
  pivot_wider( 
    names_from = cold, 
    values_from = n_obs)
```


```{r}
weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)

#check out janitor package 
```

## General summaries 

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(
    n_obs = n(), 
    mean_tmax = mean(tmax, na.rm = TRUE), 
    sd_prcp = sd(prcp), 
    median_tmax = median(tmax, na.rm = TRUE)
  )
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))
```
This is a dataframe!!!

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```


